config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :events
    root to: 'dashboard#index'
  end

  #get 'pages/home'

  devise_for :users, controllers: {
     sessions: 'users/sessions'
     }


  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  unauthenticated do
    root 'pages#home'
  end

  authenticated :user do
    root 'events#index', as: :authenticated_root
  end
  
  resources :events do
    resources :tickets, only: [:index,:new, :create, :destroy]
  end
  resources :events do
    resources :tickets, only: [:new, :create]
  end
  resource :profile, only: [:show, :edit, :update]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organizer, class_name: 'User'
  has_many :tickets
  has_many :attendees, through: :tickets, source: :user

  validates :name, :location, :date, :organizer_id, presence: true
  validates :name, uniqueness: { scope: :date, message: "An Event with the same name already exists on this date"}
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only

  layout 'admin'

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to admin_event_path(@event), notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to admin_event_path(@event), notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to admin_events_path, notice: 'Event was successfully deleted.'
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :date, :location, :price)
  end

  def admin_only
    redirect_to root_path, alert: "Access denied!" unless current_user.admin?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authorize_organizer!, only: [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
    @events
  end

  def new
    @event = current_user.organized_events.build
  end

  def create
    @event = current_user.organized_events.build(event_params)
    if @event.save
      redirect_to @event, notice: "Event was successfully created "
      else
        render "new"
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully deleted.'
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def authorize_organizer!
    redirect_to events_path, alert: 'Not authorized' unless @event.organizer == current_user
  end

  def event_params
    params.require(:event).permit(:name, :description, :location, :date)
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/edit.html.erb
<div class="container mt-5">
  <h1 class="text-center">New Events</h1>
  <h1><%= action_name.capitalize %> Event</h1>

<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field  :name, placeholder: "Enter event name" %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description, placeholder: "Enter event description" %>
  </div>

  <div>
    <%= form.label :location %>
    <%= form.text_field :location, placeholder: "Enter event location"%>
  </div>

  <div>
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>


</div>

app/views/admin/events/index.html.erb
<div class="container mt-5">
  <h1 class="text-center">Manage Events</h1>

  <%= link_to 'New Event', new_admin_event_path, class: 'btn btn-success mb-3' %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date</th>
        <th>Location</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.date %></td>
          <td><%= event.location %></td>
          <td>
            <%= link_to 'Show', admin_event_path(event), class: 'btn btn-info btn-sm' %>
            <%= link_to 'Edit', edit_admin_event_path(event), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Delete', admin_event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/events/new.html.erb
<div class="container mt-5">
  <h1 class="text-center">New Events</h1>
  <h1><%= action_name.capitalize %> Event</h1>

<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>


</div>